name: naxalibre
description: "This is Naxalibre, a custom MapLibre plugin proudly developed by @itheamc, to enhance mapping capabilities and streamline geospatial workflows."
version: 0.0.6
homepage: https://github.com/itheamc/naxalibre

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.1.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.itheamc.naxalibre
        pluginClass: NaxaLibrePlugin
      ios:
        pluginClass: NaxaLibrePlugin
      web:
        pluginClass: NaxaLibreWeb
        fileName: naxalibre_web.dart

